### ISSUE TITLE
ModuleNotFoundError: No module named 'class1_neural_network'

### ISSUE THREAD

**Issue by victorfica** [ninglab/mhcrank#1]
Hi! Im very interested in this implementation. Im triying to run the "Initialize Training" step but im getting the following error : 
  File "/mnt/d/Python_projects/mhcrank/mhcrank/train_processing_models_command.py", line 25, in <module>
    from class1_processing_predictor import Class1ProcessingPredictor
  File "/mnt/d/Python_projects/mhcrank/mhcrank/class1_processing_predictor.py", line 18, in <module>
    from class1_neural_network import DEFAULT_PREDICT_BATCH_SIZE
ModuleNotFoundError: No module named 'class1_neural_network'

where is the `class1_neural_network` module ?

**Comment by kingston487** [comment]
@victorfica, thanks for your interest in our implementation and for bringing this error to our attention. `class1_neural_network` is an unnecessary module in the current repository. I have updated modules within the repository to include any functions that were previously defined by this module and required to run our model. I tested the current version and was able to complete the training process by follow the instructions in the README. Please let us know if you have any other questions or encounter further issues.

**Comment by victorfica** [comment]
@kingston487 Thanks! I was able to run the training step, just with a minor correction in `class1_processing_neural_network.py`, becase there is a typo in line 462. 

I have another question about training results, but i will open another issue. 

Thanks
